CmentarzKomunalny/CmentarzKomunalny.Web/Controllers/GraveyardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using CmentarzKomunalny.Web.Data.Interfaces;
using CmentarzKomunalny.Web.DTOs.GraveyardDtos;

namespace CmentarzKomunalny.Web.Controllers
{
    [Route("api/graveyard")]
    [ApiController]
    public class GraveyardController : ControllerBase
    {
        private readonly IGraveyardRepo _repository;
        private readonly IMapper _mapper;
        public GraveyardController(IGraveyardRepo repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        // get all info
        [HttpGet]
        public ActionResult <IEnumerable<GraveyardReadDto>> GetGraveyardInfo()
        {
            var graveyard = _repository.GetGraveyardInfo();
            return Ok(_mapper.Map<IEnumerable<GraveyardReadDto>>(graveyard));
        }

        // do later

        // update info about graveyard
 //       [HttpPut]
 //       public ActionResult UpdateGraveyardDb(int id, GraveyardUpdateDto graveyardUpdateDto)
 //       {
 //           var graveyardRepo = _repository.
 //       }
        // patch info about graveyard
 //       [HttpPatch("{id}")]
       
    }
}

CmentarzKomunalny/CmentarzKomunalny.Web/Controllers/LodgingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using AutoMapper;
using CmentarzKomunalny.Web.Data.Interfaces;
using CmentarzKomunalny.Web.DTOs.LodgingDtos;
using CmentarzKomunalny.Web.Models.Cmentarz;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace CmentarzKomunalny.Web.Controllers
{
    // api/lodging
    [Route("api/[controller]")] // to tez trzeba z wyszukiwarka grobow polaczyc
    [ApiController]
    
    public class LodgingController : ControllerBase
    {
        private readonly ILodgingsRepo _repository; // dependency injection
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;
        public LodgingController(ILodgingsRepo repository, IMapper mapper, IConfiguration configuration)
        {
            _configuration = configuration;
            _repository = repository;
            _mapper = mapper;
        }
        // get all lodgings
        //GET api/lodging
        [HttpGet]
        public JsonResult Get()
        {
            string query = @"
                select IdLodge, LodgingType, isMonument, PeopleLimit, isReserved from dbo.Lodgings";
            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult(table);
            }
        }

    //    [Authorize(Policy = "RequireAdministratorRole")]
    //   [Authorize(Policy = "RequireEmployeeRole")]
        // SEARCHING LODGING BY ITS ID
        //GET api/lodging/LodgeById
        [HttpGet("LodgeById/{id}")]
        public ActionResult<LodgingReadDto> GetLodgeById(int id)
        {
            var lodgeId = _repository.GetLodgeById(id);
            if (lodgeId != null)
                return Ok(_mapper.Map<LodgingReadDto>(lodgeId));
            return NotFound();
        }

    //    [Authorize(Policy = "RequireAdministratorRole")]
    //    [Authorize(Policy = "RequireEmployeeRole")]
        [HttpPost]
        public JsonResult Post(Lodging lodge)
        {

            string query = @"
                insert into dbo.Lodgings values
                ('" + Convert.ToInt32(lodge.LodgingType) + @"', N'" + lodge.isMonument + @"',
                 N'" + lodge.PeopleLimit + @"', '" + lodge.isReserved + @"')";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Dodano kwaterę pomyślnie");
            }
        }

    //    [Authorize(Policy = "RequireAdministratorRole")]
    //   [Authorize(Policy = "RequireEmployeeRole")]
        [HttpPut]
        public JsonResult Put(Lodging lodge)
        {
            string query = @"
                update dbo.DeadPeople set
                LodgingType = '" + lodge.LodgingType + @"',
                isMonument = '" + lodge.isMonument + @"',
                PeopleLimit = '" + lodge.PeopleLimit + @"',
                isReserved = '" + lodge.isReserved + @"'
                where IdLodge = " + lodge.IdLodge + @"";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Zaktualizowano kwaterę pomyślnie");
            }
        }

    //    [Authorize(Policy = "RequireAdministratorRole")]
    //   [Authorize(Policy = "RequireEmployeeRole")]
        [HttpDelete("{id}")]
        public JsonResult Delete(int id)
        {
            string query = @"
                delete from dbo.Lodgings
                where IdLodge = " + id + @"";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Kwatera usunięta pomyślnie");
            }
        }

    //    [Authorize(Policy = "RequireAdministratorRole")]
    //    [Authorize(Policy = "RequireEmployeeRole")]
        // PATCH
        //PATCH api/lodging/LodgeById
        [HttpPatch("LodgeById/{id}")]
        public ActionResult PartialLodgeUpdate(int id, JsonPatchDocument<LodgingAddDto> patchDoc)
        {
            var lodgeFromRepo = _repository.GetLodgeById(id);
            if (lodgeFromRepo == null)
                return NotFound();

            var lodgeToPatch = _mapper.Map<LodgingAddDto>(lodgeFromRepo);
            patchDoc.ApplyTo(lodgeToPatch, ModelState);

            _mapper.Map(lodgeToPatch, lodgeFromRepo);
            _repository.UpdateLodge(lodgeFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }

    }
}

/*
 * public ActionResult<IEnumerable<LodgingReadDto>> GetAllLodgings()
        {
            var lodgings = _repository.GetAllLodgings();
            return Ok(_mapper.Map<IEnumerable<LodgingReadDto>>(lodgings));
        }
// add new lodge
        //POST api/lodging/
        [HttpPost]
        public ActionResult<LodgingAddDto> AddLodgeToDb(LodgingAddDto lodgeAddDto)
        {
            
            var lodgeModel = _mapper.Map<Lodging>(lodgeAddDto);
            _repository.AddLodgeToDb(lodgeModel);
            _repository.SaveChanges();
            var lodgeReadDto = _mapper.Map<LodgingReadDto>(lodgeModel);
            return CreatedAtRoute(nameof(GetLodgeById), new { Id = lodgeReadDto.IdLodge }, lodgeReadDto);
        }
// UPDATE LODGE CONTENT BY ITS ID
        //PUT api/lodging/LodgeById
        [HttpPut("LodgeById/{id}")]
        public ActionResult UpdateLodge(int id, LodgingAddDto lodgingAddDto)
        {
            var lodgeFromRepo = _repository.GetLodgeById(id);
            if (lodgeFromRepo == null)
                return NotFound();
            _mapper.Map(lodgingAddDto, lodgeFromRepo);
            _repository.UpdateLodge(lodgeFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
//DELETE api/lodging/LodgeById
        [HttpDelete("LodgeById/{id}")]
        public ActionResult DeleteLodgeFromDb(int id)
        {
            var lodgeFromRepo = _repository.GetLodgeById(id);
            if (lodgeFromRepo == null)
                return NotFound();
            _repository.DeleteLodgeFromDb(lodgeFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
*/

CmentarzKomunalny/CmentarzKomunalny.Web/Controllers/NewsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using System.Data.SqlClient;
using System.Data;
using CmentarzKomunalny.Web.DTOs.NewsDtos;
using CmentarzKomunalny.Web.Data.Interfaces;
using CmentarzKomunalny.Web.Models.Cmentarz;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;

namespace CmentarzKomunalny.Web.Controllers
{
    // api/news
    [Route("api/[controller]")] // polaczyc z 'aktualnosci'
    [ApiController]

    public class NewsController : ControllerBase
    {
        private readonly IConfiguration _configuration;
        private readonly INewsRepo _repository;
        private readonly IMapper _mapper;

        public NewsController(IConfiguration configuration, INewsRepo repository, IMapper mapper)
        {
            _configuration = configuration;
            _repository = repository;
            _mapper = mapper;
        }

        [HttpGet]
        public JsonResult Get()
        {
            string query = @"
                select Id, Title, DateOfPublication, NewsContent from dbo.News";
            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult(table);
            }
        }

        //   [Authorize(Policy = "RequireAdministratorRole")]
        //   [Authorize(Policy = "RequireEmployeeRole")]
        [HttpPost]
        public JsonResult Post(News news)
        {
            string query = @"
                insert into dbo.News values
                (N'" + news.Title + @"', N'" + news.DateOfPublication + @"',
                 N'" + news.NewsContent + @"')";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Dodano aktualność pomyślnie");
            }
        }

        //   [Authorize(Policy = "RequireAdministratorRole")]
        //   [Authorize(Policy = "RequireEmployeeRole")]
        [HttpPut]
        public JsonResult Put(News news)
        {
            string query = @"
                update dbo.News set
                Title = N'" + news.Title + @"',
                DateOfPublication = '" + news.DateOfPublication + @"',
                NewsContent = N'" + news.NewsContent + @"'
                where Id = '" + news.Id + @"'";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Zaktualizowano aktualność pomyślnie");
            }
        }

        //   [Authorize(Policy = "RequireAdministratorRole")]
        //   [Authorize(Policy = "RequireEmployeeRole")]
        [HttpDelete("{id}")]
        public JsonResult Delete(int id)
        {
            string query = @"
                delete from dbo.News
                where Id = " + id + @"";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Usunięto aktualność pomyślnie");
            }
        }
    }
}
     //   [Authorize(Policy = "RequireAdministratorRole")]
     //   [Authorize(Policy = "RequireEmployeeRole")]
        // search news by its ID
        //GET api/news
    //    [HttpGet("{id}", Name = "GetNewsById")]
    //    public ActionResult<NewsReadDto> GetNewsById(int id)
    //    {
    //        var newsId = _repository.GetNewsById(id);
    //        if (newsId != null)
    //            return Ok(_mapper.Map<NewsReadDto>(newsId));
    //        return NotFound();
    //    }



     //   [Authorize(Policy = "RequireAdministratorRole")]
     //   [Authorize(Policy = "RequireEmployeeRole")]
        // PATCH
        //PATCH api/news
    /*    [HttpPatch("{id}")]
        public ActionResult PartialNewsUpdate(int id, JsonPatchDocument<NewsAddDto> patchDoc)
        {
            var newsFromRepo = _repository.GetNewsById(id);
            if (newsFromRepo == null)
                return NotFound();

            var newsToPatch = _mapper.Map<NewsAddDto>(newsFromRepo);
            patchDoc.ApplyTo(newsToPatch, ModelState);

            _mapper.Map(newsToPatch, newsFromRepo);
            _repository.UpdateNews(newsFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
    }
    */


/*
 * // get all news
        //GET api/news
    //    [HttpGet]
    //    public ActionResult <IEnumerable<NewsReadDto>> GetAllNews()
    //    {
    //        var news = _repository.GetAllNews();
    //        return Ok(_mapper.Map<IEnumerable<NewsReadDto>>(news));
    //    }
// add new news
        //POST api/news
        [HttpPost]
        public ActionResult<NewsAddDto> AddNews(NewsAddDto newsAddDto)
        {
            var newsModel = _mapper.Map<News>(newsAddDto);
            _repository.AddNews(newsModel);
            _repository.SaveChanges();
            var newsReadDto = _mapper.Map<NewsReadDto>(newsModel);
            return CreatedAtRoute(nameof(GetNewsById), new { Id = newsReadDto.Id }, newsReadDto);
        }
// update news content by its id
        //PUT api/news
        [HttpPut("{id}")]
        public ActionResult UpdateNews(int id, NewsAddDto newsAddDto)
        {
            var newsFromRepo = _repository.GetNewsById(id);
            if (newsFromRepo == null)
                return NotFound();
            _mapper.Map(newsAddDto, newsFromRepo);
            _repository.UpdateNews(newsFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
//DELETE api/news
        [HttpDelete("{id}")]
        public ActionResult DeleteNews(int id)
        {
            var newsFromRepo = _repository.GetNewsById(id);
            if (newsFromRepo == null)
                return NotFound();
            _repository.DeleteNews(newsFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
 *
 *
 */

CmentarzKomunalny/CmentarzKomunalny.Web/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.AspNetCore.Identity;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cmentarz Komunalny</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Subject" asp-action="Index" class="navbar-brand">Cmentarz Komunalny</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (User.IsInRole("Employee") || User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="News" asp-action="Index">Aktualności</a></li>
                        <li><a asp-area="" asp-controller="Obituary" asp-action="Index">Nekrologi</a></li>
                        <li><a asp-area="" asp-controller="DeadPerson" asp-action="Index">Martwi ludzie</a></li>
                        <li><a asp-area="" asp-controller="Lodging" asp-action="Index">Kwatery</a></li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Graveyard" asp-action="Index">Informacje o cmentarzu</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Index">Dodaj pracownika</a></li>
                    }
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                </ul>
                @await Html.PartialAsync("_LoginPartial") 
                <!--<partial name="_LoginPartial" />-->
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Cmentarz Komunalny<br>Projekt zespołowy</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html> 