CmentarzKomunalny/CmentarzKomunalny.Web/Controllers/GraveyardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using CmentarzKomunalny.Web.Data.Interfaces;
using CmentarzKomunalny.Web.DTOs.GraveyardDtos;

namespace CmentarzKomunalny.Web.Controllers
{
    [Route("api/graveyard")]
    [ApiController]
    public class GraveyardController : ControllerBase
    {
        private readonly IGraveyardRepo _repository;
        private readonly IMapper _mapper;
        public GraveyardController(IGraveyardRepo repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        // get all info
        [HttpGet]
        public ActionResult <IEnumerable<GraveyardReadDto>> GetGraveyardInfo()
        {
            var graveyard = _repository.GetGraveyardInfo();
            return Ok(_mapper.Map<IEnumerable<GraveyardReadDto>>(graveyard));
        }

        // do later

        // update info about graveyard
 //       [HttpPut]
 //       public ActionResult UpdateGraveyardDb(int id, GraveyardUpdateDto graveyardUpdateDto)
 //       {
 //           var graveyardRepo = _repository.
 //       }
        // patch info about graveyard
 //       [HttpPatch("{id}")]
       
    }
}

CmentarzKomunalny/CmentarzKomunalny.Web/Controllers/NewsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using System.Data.SqlClient;
using System.Data;
using CmentarzKomunalny.Web.DTOs.NewsDtos;
using CmentarzKomunalny.Web.Data.Interfaces;
using CmentarzKomunalny.Web.Models.Cmentarz;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;

namespace CmentarzKomunalny.Web.Controllers
{
    // api/news
    [Route("api/[controller]")] // polaczyc z 'aktualnosci'
    [ApiController]

    public class NewsController : ControllerBase
    {
        private readonly IConfiguration _configuration;
        private readonly INewsRepo _repository;
        private readonly IMapper _mapper;

        public NewsController(IConfiguration configuration, INewsRepo repository, IMapper mapper)
        {
            _configuration = configuration;
            _repository = repository;
            _mapper = mapper;
        }

        [HttpGet]
        public JsonResult Get()
        {
            string query = @"
                select Id, Title, DateOfPublication, NewsContent from dbo.News";
            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult(table);
            }
        }

        //   [Authorize(Policy = "RequireAdministratorRole")]
        //   [Authorize(Policy = "RequireEmployeeRole")]
        [HttpPost]
        public JsonResult Post(News news)
        {
            string query = @"
                insert into dbo.News values
                (N'" + news.Title + @"', N'" + news.DateOfPublication + @"',
                 N'" + news.NewsContent + @"')";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Dodano aktualność pomyślnie");
            }
        }

        //   [Authorize(Policy = "RequireAdministratorRole")]
        //   [Authorize(Policy = "RequireEmployeeRole")]
        [HttpPut]
        public JsonResult Put(News news)
        {
            string query = @"
                update dbo.News set
                Title = N'" + news.Title + @"',
                DateOfPublication = '" + news.DateOfPublication + @"',
                NewsContent = N'" + news.NewsContent + @"'
                where Id = '" + news.Id + @"'";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Zaktualizowano aktualność pomyślnie");
            }
        }

        //   [Authorize(Policy = "RequireAdministratorRole")]
        //   [Authorize(Policy = "RequireEmployeeRole")]
        [HttpDelete("{id}")]
        public JsonResult Delete(int id)
        {
            string query = @"
                delete from dbo.News
                where Id = " + id + @"";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Usunięto aktualność pomyślnie");
            }
        }
    }
}
     //   [Authorize(Policy = "RequireAdministratorRole")]
     //   [Authorize(Policy = "RequireEmployeeRole")]
        // search news by its ID
        //GET api/news
    //    [HttpGet("{id}", Name = "GetNewsById")]
    //    public ActionResult<NewsReadDto> GetNewsById(int id)
    //    {
    //        var newsId = _repository.GetNewsById(id);
    //        if (newsId != null)
    //            return Ok(_mapper.Map<NewsReadDto>(newsId));
    //        return NotFound();
    //    }



     //   [Authorize(Policy = "RequireAdministratorRole")]
     //   [Authorize(Policy = "RequireEmployeeRole")]
        // PATCH
        //PATCH api/news
    /*    [HttpPatch("{id}")]
        public ActionResult PartialNewsUpdate(int id, JsonPatchDocument<NewsAddDto> patchDoc)
        {
            var newsFromRepo = _repository.GetNewsById(id);
            if (newsFromRepo == null)
                return NotFound();

            var newsToPatch = _mapper.Map<NewsAddDto>(newsFromRepo);
            patchDoc.ApplyTo(newsToPatch, ModelState);

            _mapper.Map(newsToPatch, newsFromRepo);
            _repository.UpdateNews(newsFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
    }
    */


/*
 * // get all news
        //GET api/news
    //    [HttpGet]
    //    public ActionResult <IEnumerable<NewsReadDto>> GetAllNews()
    //    {
    //        var news = _repository.GetAllNews();
    //        return Ok(_mapper.Map<IEnumerable<NewsReadDto>>(news));
    //    }
// add new news
        //POST api/news
        [HttpPost]
        public ActionResult<NewsAddDto> AddNews(NewsAddDto newsAddDto)
        {
            var newsModel = _mapper.Map<News>(newsAddDto);
            _repository.AddNews(newsModel);
            _repository.SaveChanges();
            var newsReadDto = _mapper.Map<NewsReadDto>(newsModel);
            return CreatedAtRoute(nameof(GetNewsById), new { Id = newsReadDto.Id }, newsReadDto);
        }
// update news content by its id
        //PUT api/news
        [HttpPut("{id}")]
        public ActionResult UpdateNews(int id, NewsAddDto newsAddDto)
        {
            var newsFromRepo = _repository.GetNewsById(id);
            if (newsFromRepo == null)
                return NotFound();
            _mapper.Map(newsAddDto, newsFromRepo);
            _repository.UpdateNews(newsFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
//DELETE api/news
        [HttpDelete("{id}")]
        public ActionResult DeleteNews(int id)
        {
            var newsFromRepo = _repository.GetNewsById(id);
            if (newsFromRepo == null)
                return NotFound();
            _repository.DeleteNews(newsFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
 *
 *
 */

CmentarzKomunalny/CmentarzKomunalny.Web/Controllers/ObituaryController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using CmentarzKomunalny.Web.DTOs.NewsDtos;
using CmentarzKomunalny.Web.Data.Interfaces;
using CmentarzKomunalny.Web.Models.Cmentarz;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.Extensions.Configuration;
using CmentarzKomunalny.Web.DTOs.ObituaryDtos;
using System.Data;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Authorization;

namespace CmentarzKomunalny.Web.Controllers
{
    // api/obituary
    [Route("api/[controller]")] // polaczyc z 'nekrologi'
    [ApiController]
    
    public class ObituaryController : ControllerBase
    {
        private readonly IConfiguration _configuration;
        private readonly IObituaryRepo _repository;
        private readonly IMapper _mapper;
        public ObituaryController(IConfiguration configuration, IObituaryRepo repository, IMapper mapper)
        {
            _configuration = configuration;
            _repository = repository;
            _mapper = mapper;
        }

        [HttpGet]
        public JsonResult Get()
        {
            string query = @"
                select Id, Name, DateOfDeath_Obituary, ObituaryContent from dbo.Obituaries";
            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult(table);
            }
        }

    //    [Authorize(Policy = "RequireAdministratorRole")]
    //    [Authorize(Policy = "RequireEmployeeRole")]
        [HttpPost]
        public JsonResult Post(Obituary ob)
        {
            string query = @"
                insert into dbo.Obituaries values
                (N'" + ob.Name + @"', N'" + ob.DateOfDeath_Obituary + @"',
                 N'" + ob.ObituaryContent + @"')";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Dodano nekrolog pomyślnie");
            }
        }
    //    [Authorize(Policy = "RequireAdministratorRole")]
    //    [Authorize(Policy = "RequireEmployeeRole")]
        [HttpPut]
        public JsonResult Put(Obituary ob)
        {
            string query = @"
                update dbo.Obituaries set
                Name = N'" + ob.Name + @"',
                DateOfDeath_Obituary = '" + ob.DateOfDeath_Obituary + @"',
                ObituaryContent = N'" + ob.ObituaryContent + @"'
                where Id = '" + ob.Id + @"'";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Zaktualizowano nekrolog pomyślnie");
            }
        }
    //    [Authorize(Policy = "RequireAdministratorRole")]
    //    [Authorize(Policy = "RequireEmployeeRole")]
        [HttpDelete("{id}")]
        public JsonResult Delete(int id)
        {
            string query = @"
                delete from dbo.Obituaries
                where Id = " + id + @"";

            DataTable table = new DataTable();
            string sqlDataSource = _configuration.GetConnectionString("CmentarzConnectionTEST");
            SqlDataReader myReader;
            using (SqlConnection myCon = new SqlConnection(sqlDataSource))
            {
                myCon.Open();
                using (SqlCommand myCommand = new SqlCommand(query, myCon))
                {
                    myReader = myCommand.ExecuteReader();
                    table.Load(myReader); ;

                    myReader.Close();
                    myCon.Close();
                }
                return new JsonResult("Usunięto nekrolog pomyślnie");
            }
        }

    //    [Authorize(Policy = "RequireAdministratorRole")]
    //    [Authorize(Policy = "RequireEmployeeRole")]
        // search obituary by its ID
        //GET api/obituary
        [HttpGet("{id}", Name = "GetObituaryById")]
        public ActionResult<ObituaryReadDto> GetObituaryById(int id)
        {
            var obituaryId = _repository.GetObituaryById(id);
            if (obituaryId != null)
                return Ok(_mapper.Map<ObituaryReadDto>(obituaryId));
            return NotFound();
        }

     //   [Authorize(Policy = "RequireAdministratorRole")]
     //   [Authorize(Policy = "RequireEmployeeRole")]
        // PATCH
        //PATCH api/obituary
        [HttpPatch("{id}")]
        public ActionResult PartialObituaryUpdate(int id, JsonPatchDocument<ObituaryAddDto> patchDoc)
        {
            var obituaryFromRepo = _repository.GetObituaryById(id);
            if (obituaryFromRepo == null)
                return NotFound();

            var obituaryToPatch = _mapper.Map<ObituaryAddDto>(obituaryFromRepo);
            patchDoc.ApplyTo(obituaryToPatch, ModelState);

            _mapper.Map(obituaryToPatch, obituaryFromRepo);
            _repository.UpdateObituary(obituaryFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
    }
}

/*
 * //      [HttpGet]
        //      public ActionResult<IEnumerable<ObituaryReadDto>> GetAllObituaries()
        //      {
        //          var obituaries = _repository.GetAllObituaries();
        //          return Ok(_mapper.Map<IEnumerable<ObituaryReadDto>>(obituaries));
        //     }
// add new obituary
        //POST api/obituary
        [HttpPost]
        public ActionResult<ObituaryAddDto> AddObituary(ObituaryAddDto obituaryAddDto)
        {
            var obituaryModel = _mapper.Map<Obituary>(obituaryAddDto);
            var obituaryReadDto = _mapper.Map<NewsReadDto>(obituaryModel);
            _repository.AddObituary(obituaryModel);
            _repository.SaveChanges();
            return CreatedAtRoute(nameof(GetObituaryById), new { Id = obituaryReadDto.Id }, obituaryReadDto);
        }
// update obituary content by its id
        //PUT api/obituary
        [HttpPut("{id}")]
        public ActionResult UpdateObituary(int id, ObituaryAddDto obituaryAddDto)
        {
            var obituaryFromRepo = _repository.GetObituaryById(id);
            if (obituaryFromRepo == null)
                return NotFound();
            _mapper.Map(obituaryAddDto, obituaryFromRepo);
            _repository.UpdateObituary(obituaryFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
     //DELETE api/obituary
        [HttpDelete("{id}")]
        public ActionResult DeleteObituary(int id)
        {
            var obituaryFromRepo = _repository.GetObituaryById(id);
            if (obituaryFromRepo == null)
                return NotFound();
            _repository.DeleteObituary(obituaryFromRepo);
            _repository.SaveChanges();
            return NoContent();
        }
    }
 */

CmentarzKomunalny/CmentarzKomunalny.Web/Views/Shared/ButtonsOnPage.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@{

}
@if (User.IsInRole("Administrator"))
{
    <a asp-action="Index" asp-controller="Admin"
       class="btn btn-primary mb-3" style="width:auto">
        Strona główna admina
    </a>
    <a asp-action="RegisterAdmin" asp-controller="Admin"
       class="btn btn-primary mb-3" style="width:auto">
        Nowy admin
    </a>
    <a asp-action="RegisterEmployee" asp-controller="Admin"
       class="btn btn-primary mb-3" style="width:auto">
        Nowy pracownik
    </a>
    <a asp-action="BlockEmployee" asp-controller="Admin"
       class="btn btn-primary mb-3" style="width:auto">
        Zablokuj pracownika
    </a>
    <a asp-action="UnblockEmployee" asp-controller="Admin"
       class="btn btn-primary mb-3" style="width:auto">
        Odblokuj pracownika
    </a>
    <a asp-action="ListUsers" asp-controller="Admin"
       class="btn btn-primary mb-3" style="width:auto">
        Spis użytkowników
    </a>
}

@if (User.IsInRole("Employee"))
{
        <a asp-action="Home" asp-controller="Home"
           class="btn btn-primary mb-3" style="width:auto">
            Strona główna pracownika
        </a>
        <a href="paneladministratora"
           class="btn btn-primary mb-3" style="width:auto">
            Panel pracownika serwisu
        </a>
}

CmentarzKomunalny/CmentarzKomunalny.Web/Views/Shared/NotFound.cshtml
notfoundbu

CmentarzKomunalny/CmentarzKomunalny.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.AspNetCore.Identity;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cmentarz Komunalny</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Admin" asp-action="Index" class="navbar-brand">Cmentarz Komunalny</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                  
                    <li><a asp-area="" asp-controller="Obituary" asp-action="Index"></a>Panel obsługi administratora</li>
                    <li><a asp-area="" asp-controller="DeadPerson" asp-action="Index">Panel obsługi pracownika</a></li>
                    <li><a asp-area="" asp-controller="News" asp-action="Index">Powrót do strony głównej cmentarza</a></li>
                    <li><a asp-area="" asp-controller="Graveyard" asp-action="Index">Informacje o cmentarzu</a></li>

                    
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                </ul>

            </div>
        </div>
    </nav>



    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Cmentarz Komunalny<br>Projekt zespołowy</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    
    </body>
</html>